# -*- coding: utf-8 -*-
"""actions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IEweX-Pr3LSj_HsfCG-5w4LhGah2W3S1
"""

# installation of packages
!pip install rasa-nlu==0.13.2 
!pip install sklearn_crfsuite
!pip install rasa_core
!pip install Action

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
import requests
from rasa_core_sdk import Action
from rasa_core_sdk.events import SlotSet

!git clone https://github.com/tapasweni-pathak/Horoscope-API

class GetTodaysHoroscope(Action): 
    def name(self):     
      return "get_todays_horoscope" 
    def run(self, dispatcher, tracker, domain): 
        # type: (Dispatcher, DialogueStateTracker, Domain) -> List[Event] 
        user_horoscope_sign = tracker.get_slot('horoscope_sign')   
        base_url = "http://horoscope-api.herokuapp.com/horoscope/{day}/{sign}" 
        url = base_url.format(**{'day': "today", 'sign': user_horoscope_sign})   
        #http://horoscope-api.herokuapp.com/horoscope/today/capricorn     
        res = requests.get(url)      
        todays_horoscope = res.json()['horoscope']   
        response = "Your today's horoscope:\n{}".format(todays_horoscope) 
        dispatcher.utter_message(response)  
        return [SlotSet("horoscope_sign", user_horoscope_sign)]

GetTodaysHoroscope()

class SubscribeUser(Action):
    def name(self):
        return "subscribe_user"

    def run(self, dispatcher, tracker, domain):
        # type: (Dispatcher, DialogueStateTracker, Domain) -> List[Event]
       
        subscribe = tracker.get_slot('subscribe')
        if subscribe == "True":
            response = "You're successfully subscribed"
        if subscribe == "False":
            response = "You're successfully unsubscribed"

        dispatcher.utter_message(response)
        return [SlotSet("subscribe", subscribe)]

